# Generated by Django 6.0.4 on 2026-04-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprel23', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
