# Generated by Django 6.0.4 on 2026-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('brend', models.CharField(max_length=244)),
                ('info', models.TextField(blank=True)),
            ],
        ),
    ]
